# Data import

In [51]:
import pandas as pd
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 1000)
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [52]:
listings = pd.read_csv('../data/data_jan_listings_3plus.csv',low_memory=False)

In [53]:
def str_to_price(strn):
    '''The function converts a price entry from string to float and removes the $ character'''
    
    if type(strn)== str:
        return float(strn.strip('$').replace(',',''))
    return strn


def price_tonumerical(df, price_columns):
    '''This function takes as input a dataframe and a list of price column names and converts the columnns to
    floats'''
    
    for column in price_columns:
        df[[column]] = df[[column]].applymap(str_to_price)
    return df

def calculate_cleaning_ratio(df):
    '''This function calculates the ratio of cleaning fee to the nightly price'''
    
    df['cleaning_ratio']=round(df['cleaning_fee']/df['price'],2)
    return df

def calculate_deposit_ratio(df):
    '''This function calculates the ratio of security deposit fee to the nightly price'''
    
    df['deposit_ratio']=round(df['security_deposit']/df['price'],2)
    return df


price_columns=['price', 'security_deposit', 'cleaning_fee', 'extra_people']
price_tonumerical(listings, price_columns)
calculate_cleaning_ratio(listings)

,id,name,summary,space,description,experiences_offered,neighborhood_overview,notes,transit,access,interaction,house_rules,host_since,host_location,host_about,host_response_time,host_response_rate,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_identity_verified,street,neighbourhood_cleansed,zipcode,latitude,longitude,is_location_exact,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,availability_30,availability_60,availability_90,availability_365,number_of_reviews,number_of_reviews_ltm,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,reviews_per_month,cleaning_ratio
0,11551.0,Arty and Bright London Apartment in Zone 2,Unlike most rental apartments out there my fla...,"Amenities Bedding: 1 Double bed, 1 living room...",Unlike most rental apartments out there my fla...,family,Not even 10 minutes by metro from Victoria Sta...,No Smoking (very strict) Check-in time is afte...,Tons of buses (24hrs) go into central London f...,Guest will have access to the entire apartment,No interaction with guests as you book the ent...,No Smoking (very strict) No pets are allowed i...,2009-10-03,"London, England, United Kingdom","Hello, I'm a friendly Italian man with a very ...",within an hour,100%,Brixton,3.0,3.0,"['email', 'phone', 'reviews', 'jumio', 'offlin...",t,"London, United Kingdom",Lambeth,SW9 8DG,51.46225,-0.11732000000000001,t,Apartment,Entire home/apt,4.0,1.0,1.0,1.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,Kitchen,""Paid par...",88.0,$645.00,"$2,350.00",400.0,30.0,2.0,25.0,2.0,180.0,17.0,42,72,344,186,3.0,2010-03-21,2019-11-17,92.0,9.0,9.0,10.0,10.0,9.0,9.0,t,strict_14_with_grace_period,f,t,1.56,0.34
1,13913.0,Holiday London DB Room Let-on going,My bright double bedroom with a large window h...,"Hello Everyone, I'm offering my lovely double ...",My bright double bedroom with a large window h...,business,Finsbury Park is a friendly melting pot commun...,For art lovers I can give guest my Tate Member...,The flat only a 10 minute walk to Finsbury Par...,Guest will have access to the self catering ki...,I like to have little chats with my guest over...,I'm an artist and have my artwork up on the wa...,2009-11-16,"London, England, United Kingdom",I am a Multi-Media Visual Artist and Creative ...,within a few hours,70%,LB of Islington,4.0,4.0,"['email', 'phone', 'facebook', 'reviews', 'off...",t,"Islington, Greater London, United Kingdom",Islington,N4 3,51.568020000000004,-0.11120999999999999,t,Apartment,Private room,2.0,1.0,1.0,0.0,Real Bed,"{TV,""Cable TV"",Wifi,Kitchen,""Paid parking off ...",65.0,$333.00,"$1,176.00",100.0,15.0,1.0,15.0,1.0,29.0,30.0,60,90,365,20,6.0,2010-08-18,2019-11-25,97.0,10.0,10.0,10.0,10.0,9.0,9.0,f,moderate,f,f,0.17,0.23
2,15400.0,Bright Chelsea Apartment. Chelsea!,Lots of windows and light. St Luke's Gardens ...,Bright Chelsea Apartment This is a bright one...,Lots of windows and light. St Luke's Gardens ...,romantic,It is Chelsea.,The building next door is in the process of be...,The underground stations are South Kensington ...,There are two wardrobes for guests exclusive u...,If I am in the country I like to welcome my gu...,NO SMOKING PLEASE.. No unauthorised guests. No...,2009-12-05,"Kensington, England, United Kingdom","English, grandmother, I have travelled quite ...",within a few hours,100%,Chelsea,1.0,1.0,"['email', 'phone', 'reviews', 'jumio', 'govern...",t,"London, United Kingdom",Kensington and Chelsea,SW3,51.48796,-0.16898,t,Apartment,Entire home/apt,2.0,1.0,1.0,1.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",100.0,$600.00,"$2,250.00",150.0,50.0,2.0,0.0,10.0,50.0,17.0,33,46,179,88,7.0,2009-12-21,2019-09-23,96.0,10.0,10.0,10.0,10.0,10.0,9.0,t,strict_14_with_grace_period,t,t,0.72,0.50
3,17402.0,Superb 3-Bed/2 Bath & Wifi: Trendy W1,You'll have a wonderful stay in this superb mo...,"This is a wonderful very popular beautiful, sp...",You'll have a wonderful stay in this superb mo...,none,"Location, location, location! You won't find b...",This property has new flooring throughout. Gue...,You can walk to tourist London or take numerou...,Full use of whole independent apartment,"Always available by email or phone (before, du...",* The apartment benefits from new flooring thr...,2010-01-04,"London, England, United Kingdom",We are Liz and Jack. We manage a number of ho...,within an hour,100%,Fitzrovia,18.0,18.0,"['email', 'phone', 'reviews', 'jumio', 'offlin...",t,"London, Fitzrovia, United Kingdom",Westminster,W1T4BP,51.52098,-0.14002,t,Apartment,Entire home/apt,6.0,2.0,3.0,3.0,Real Bed,"{TV,Wifi,Kitchen,""Paid parking off premises"",E...",300.0,"$1,378.00",NaN,350.0,65.0,4.0,10.0,3.0,365.0,18.0,40,40,250,42,3.0,2011-03-21,2019-11-02,94.0,10.0,9.0,9.0,9.0,10.0,9.0,t,strict_14_with_grace_period,f,f,0.39,0.22
4,25023.0,All-comforts 2-bed flat near Wimbledon tennis,"Large, all comforts, 2-bed flat; first floor; ...",10 mins walk to Southfields tube and Wimbledon...,"Large, all comforts, 2-bed flat; first floor; ...",none,This is a leafy residential area with excellen...,Non-smokers only. No pets.,Free off-street parking; buses to Richmond/Too...,Entire flat; use of communal gardens.,I'm happy to provide you with any helpful hint...,No smoking. No parties. No loud music after 10...,2010-04-03,"Rome, Lazio, Italy","Hi, I'm a sociologist/anthropologist, NLP exec...",within an hour,100%,Wimbledon,1.0,1.0,"['email', 'phone', 'reviews', 'jumio', 'offlin...",f,"Wimbledon, London, United Kingdom",Wandsworth,SW19 6QH,51.446870000000004,-0.21874000000000002,t,Apartment,Entire home/apt,4.0,1.0,2.0,2.0,Real Bed,"{TV,Wifi,Kitchen,""Free parking on premises"",El...",65.0,$630.00,"$2,515.00",250.0,50.0,2.0,11.0,90.0,1125.0,0.0,1,1,101,34,8.0,2016-03-05,2019-09-15,93.0,10.0,10.0,9.0,10.0,9.0,9.0,t,moderate,f,f,0.73,0.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51745,41172620.0,Triple/Twin Private Room Victoria Westminster,This is a private room near Victoria Station f...,This fantastic house is placed in one of the b...,This is a private room near Victoria Station f...,none,Various choices of locals to the area includin...,Early check in: £15 Late check out: £20,"The space is in the best location of London, S...",Guests will have a bedroom with a spacious sha...,Guests will have a Twin/King bedroom with a sp...,NaN,2017-08-24,"England, United Kingdom",Positive minded person :-),within an hour,99%,Westminster,12.0,12.0,"['email', 'phone', 'reviews', 'jumio', 'offlin...",f,"Greater London, England, United Kingdom",Westminster,SW1V 1ER,51.49405,-0.13792000000000001,f,Townhouse,Private room,3.0,2.0,1.0,3.0,Real Bed,"{Internet,Wifi,Kitchen,""Paid parking off premi...",59.0,NaN,NaN,100.0,8.0,1.0,10.0,1.0,1125.0,19.0,41,64,336,3,3.0,2019-12-31,2020-01-02,100.0,10.0,10.0,10.0,10.0,10.0,10.0,t,strict_14_with_grace_period,f,f,3.00,0.14
51746,41235386.0,The Diamond,*✓ NEW BARGAIN✓* *BRAND NEW FITTED 3 BED BIG ...,*All in all the property has been finished up ...,*✓ NEW BARGAIN✓* *BRAND NEW FITTED 3 BED BIG ...,none,With just 5-6 minutes walk away from the Wimbl...,Strictly no loud music after 10:00pm as the ho...,Should you wish to stay in Wimbledon itself yo...,*Self check-in *Well leave the whole newly dec...,"* Whilst you are staying at our house, we wil...",Not suitable for infants ( under 2 years) No s...,2019-12-25,"England, United Kingdom",I'm professional working in the tourism indust...,within an hour,100%,NaN,2.0,2.0,"['email', 'phone', 'offline_government_id', 's...",f,"Greater London, England, United Kingdom",Merton,SW19 4JD,51.41483,-0.2176,f,House,Entire home/apt,8.0,2.0,3.0,3.0,Real Bed,"{TV,Wifi,Kitchen,""Free parking on premises"",He...",300.0,NaN,NaN,NaN,NaN,1.0,0.0,1.0,1125.0,0.0,0,0,253,3,3.0,2020-01-06,2020-01-09,100.0,10.0,10.0,10.0,10.0,10.0,10.0,t,flexible,f,f,3.00,NaN
51747,41254738.0,GREAT DOUBLE ROOM NEAR TOWER BRIDGE,Airy and cosy room has stunning views over Lon...,NaN,Airy and cosy room has stunning views over Lon...,none,NaN,NaN,NaN,NaN,NaN,NaN,2019-10-08,"London, England, United Kingdom",Love to travel and enjoy new experiences. Nati...,within an hour,97%,NaN,0.0,0.0,"['phone', 'offline_government_id', 'selfie', '...",f,"Greater London, England, United Kingdom",Tower Hamlets,E1 1NZ,51.51514,-0.06551,f,Apartment,Private room,2.0,1.0,1.0,1.0,Real Bed,"{Wifi,Kitchen,Heating,Washer,Dryer,""Smoke dete...",48.0,NaN,NaN,0.0,5.0,1.0,0.0,1.0,1125.0,9.0,30,55,235,3,3.0,2020-01-05,2020-01-07,100.0,10.0,10.0,10.0,10.0,10.0,10.0,t,strict_14_with_grace_period,f,f,3.00,0.10
51748,41256620.0,Airy Room View Stunning London Views,The apartment is very well located 5 mins walk...,NaN,The apartment is very well located 5 mins walk...,none,NaN,NaN,NaN,NaN,NaN,NaN,2019-10-08,"London, England, United Kingdom",Love to travel and enjoy new experiences. Nati...,within an hour,97%,NaN,0.0,0.0,"['phone', 'offline_government_id', 'selfie', '...",f,"Greater London, England, United Kingdom",Tower Hamlets,E1 1NZ,51.515859999999996,-0.06619,f,Apartment,Private room,3.0,1.0,1.0,2.0,Real Bed,"{Wifi,Kitchen,Heating,Washer,Dryer,""Smoke dete...",58.0,NaN,NaN,0.0,5.0,1.0,0.0,1.0,1125.0,20.0,45,75,282,3,3.0,2020-01-05,2020-01-07,100.0,10.0,10.0,10.0,9.0,10.0,10.0,t,strict_14_with_grace_period,f,f,3.00,0.09
51749,41256815.0,Lovely Double Room in Central with London Views,Great Double Room in the city. Qient convient ...,NaN,Great Double Room in the city. Qient convient ...,none,NaN,NaN,NaN,NaN,NaN,NaN,2019-10-08,"London, England, United Kingdom",Love to travel and enjoy new experiences. Nati...,within an hour,97%,NaN,0.0,0.0,"['phone', 'offline_government_id', 'selfie', '...",f,"Greater London, England, United Kingdom",Tower Hamlets,E1 1NZ,51.515609999999995,-0.0662,f,Apartment,Private room,2.0,1.0,1.0,1.0,Real Bed,"{Wifi,Kitchen,Heating,Washer,Dryer,""Smoke dete...",45.0,NaN,NaN,0.0,4.0,1.0,0.0,1.0,1125.0,18.0,47,77,257,3,3.0,2020-01-05,2020-01-07,100.0,10.0,10.0,10.0,10.0,10.0,10.0,t,strict_14_with_grace_period,f,f,3.00,0.09

# Clusters database building

In [54]:
def price_cat(x,pctl):
    '''Transforms an absolute price into a price category, given a list of percentiles'''
    if x <pctl[1]:
        return 'very_cheap'
    elif x >=pctl[1] and x <pctl[3]:
        return 'cheap'
    elif x >=pctl[3] and x <pctl[5]:
        return 'average'
    elif x >=pctl[5] and x <pctl[7]:
        return 'expensive'
    return 'very_expensive'

def clustering(data):
    '''Returns a dataframe containing the relevant clustering variables'''
    #pctl=[]
    columns=['location', 'price-boroughwise', 'property_type', 'review_scores_rating']
    cluster_df = pd.DataFrame(columns=columns)
    #for p in range(1,10):
    #    pctl.append(np.nanpercentile(data['price'], 10*p))
    #
    #cluster_df['price-citywise']=data['price'].apply(lambda x:price_cat(x,pctl))
    percentiles=dict()
    neighbourhoods = listings['neighbourhood_cleansed'].unique()
    for neigh in neighbourhoods:
        neigh_listings = listings[listings['neighbourhood_cleansed'] == neigh]
        indices= neigh_listings.index.values.tolist()
        pctl=[]
        for p in range(1,10):
            pctl.append(np.nanpercentile(neigh_listings['price'], 10*p))
        #neigh_listings['price'].apply(lambda x:price_cat(x,pctl))
        percentiles[neigh] = pctl
        for index in indices:
            cluster_df.loc[index,'price-boroughwise']=price_cat(neigh_listings.loc[index,'price'],pctl)
            
    
    bedroom_convert = {0.0: 'small',
                  1.0: 'small',
                  2.0: 'large',
                  3.0: 'large', 4.0: 'large',5.0: 'large',6.0: 'large',7.0: 'large',
                   8.0: 'large',9.0: 'large',10.0: 'large',11.0: 'large',
                   16.0: 'large',22.0: 'large'}
    cluster_df['property_type'] =  data['bedrooms'].map(bedroom_convert)
    cluster_df['room/apt']=data[['room_type']].applymap(lambda x: 'apartment' if x == 'Entire home/apt' else 'room')# if x == 'Private room' else 'Other'))
    
    cluster_df['location']=data['neighbourhood_cleansed']
    
    cluster_df['review_scores_rating']=data['review_scores_rating']
    
    cluster_df['property_type'] = cluster_df.apply(lambda x: 'room' if x['room/apt']== 'room' else x['property_type'], axis=1)
    cluster_df['listing_id'] = data['id']
    cluster_df['lat'] = data['latitude']
    cluster_df['lon'] = data['longitude']
    cluster_df=cluster_df.drop(columns='room/apt')
    cluster_df['cluster'] = "L:" + cluster_df['location'] + "_P:" + cluster_df['price-boroughwise'] + "_S:" + cluster_df['property_type']
    #matching_table = cluster_df.copy()
    #matching_table = matching_table.groupby(['location','price-boroughwise','property_type']).count().reset_index().drop(columns='review_scores_rating')
    #matching_table['cluster_id'] = matching_table.index
    
    return cluster_df, percentiles

clusters, percentiles=clustering(listings)

/Users/lcavicchia/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/numpy/lib/nanfunctions.py:1368: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [55]:
clusters

,location,price-boroughwise,property_type,review_scores_rating,listing_id,lat,lon,cluster
0,Lambeth,expensive,small,92.0,11551.0,51.46225,-0.11732000000000001,L:Lambeth_P:expensive_S:small
33,Lambeth,cheap,room,98.0,53242.0,51.47075,-0.12913,L:Lambeth_P:cheap_S:room
34,Lambeth,expensive,small,96.0,53245.0,51.47246,-0.12727,L:Lambeth_P:expensive_S:small
50,Lambeth,cheap,room,96.0,72913.0,51.48064,-0.11439,L:Lambeth_P:cheap_S:room
51,Lambeth,cheap,large,98.0,73431.0,51.46295,-0.11199999999999999,L:Lambeth_P:cheap_S:large
...,...,...,...,...,...,...,...,...
51047,Sutton,expensive,small,100.0,39963193.0,51.3577,-0.13601,L:Sutton_P:expensive_S:small
51074,Sutton,expensive,small,98.0,39988769.0,51.35737,-0.21677,L:Sutton_P:expensive_S:small
51098,Sutton,very_expensive,small,40.0,40019636.0,51.37853,-0.21886999999999998,L:Sutton_P:very_expensive_S:small
51255,Sutton,expensive,large,60.0,40147104.0,51.34812,-0.19767,L:Sutton_P:expensive_S:large
51438,Sutton,expensive,small,88.0,40364721.0,51.3555,-0.21603000000000003,L:Sutton_P:expensive_S:small

In [6]:
def listing_to_cluster(listing_id, clusters):
    cluster_id = clusters[clusters['listing_id']==listing_id].iloc[0]['cluster']
    
    return cluster_id

In [7]:
location = clusters[clusters['listing_id']==53242][['location']]
price = clusters[clusters['listing_id']==53242][['price-boroughwise']]
ptype = clusters[clusters['listing_id']==53242][['property_type']]
cluster = matching_table[(matching_table['location'] == location ) &  (matching_table['price-boroughwise'] == price ) &\
              (matching_table['property_type'] == ptype )\
            ]
cluster

NameError: name 'matching_table' is not defined

In [ ]:
listing_to_cluster(53242, clusters)

In [56]:
clusters.to_csv('../data/jan/clusters.csv')
#matching_table.to_csv('../data/jan/clusters_table.csv')

In [ ]:
clusters

In [ ]:


def user_ranking(location, price, size, listing_id, clusters):
    #tmp= clusters[(clusters['listing_id'] == listing_id )]
    #rating=tmp['review_scores_rating']
    
    price_c=price_cat(price,percentiles[location])
    
    
    cluster = clusters[(clusters['location'] == location ) &  (clusters['price-boroughwise'] == price_c ) &\
              (clusters['property_type'] == size )\
            ].copy()
    cluster['ranking'] = cluster['review_scores_rating'].rank(method='min',ascending=False)
    cluster_average = cluster['review_scores_rating'].mean()
    user_rank =int(cluster[cluster['listing_id']== listing_id].iloc[0].loc['ranking'])
    return user_rank, cluster_average, cluster.shape[0]
    

user_rank, mean_rating, cluster_size=user_ranking('Hackney', 120, 'large', 102391, clusters)

print(f"Out of {cluster_size} similar properties with an average rating of {round(mean_rating/20,2)}, your listing \
is ranked n. {user_rank}")

In [ ]:
user_rank, mean_rating, cluster_size

In [ ]:
def top_rated(location, price, size, clusters, top=10):
    
    price_c=price_cat(price,percentiles[location])
    
    
    cluster = clusters[(clusters['location'] == location ) &  (clusters['price-boroughwise'] == price_c ) &\
              (clusters['property_type'] == size )\
            ].copy()
    cluster['ranking'] = cluster['review_scores_rating'].rank(method='min',ascending=False)
    
    sorted_cluster = cluster.sort_values(by='ranking')
    
    nrows= round(cluster.shape[0]/ top)
    return sorted_cluster.iloc[:nrows].listing_id
    #return sorted_cluster.iloc[:nrows].index.values.tolist()

In [ ]:
top = top_rated('Hackney', 120, 'large', clusters)

In [ ]:
def cluster_selection(location, price, size, clusters):
    price_c=price_cat(price,percentiles[location])
    cluster = clusters[(clusters['location'] == location ) &  (clusters['price-boroughwise'] == price_c ) &\
              (clusters['property_type'] == size )\
            ].copy()
    return cluster
cluster_selection('Hackney', 120, 'large', clusters)

In [ ]:
def cluster_mapping(location, price, size, clusters, listings):
    
    price_c=price_cat(price,percentiles[location])
    cluster = clusters[(clusters['location'] == location ) &  (clusters['price-boroughwise'] == price_c ) &\
              (clusters['property_type'] == size )\
            ].copy()
    
    indices = cluster.index.values.tolist()
    coordinates = listings.iloc[indices][['latitude','longitude']]
    return coordinates

In [ ]:
cluster_mapping('Hackney', 120, 'large', clusters,listings)

In [ ]:
matching_table  = clusters.drop(columns=['listing_id']).copy()

In [ ]:
matching_table

In [ ]:
matching_table = matching_table.groupby(['location','price-boroughwise','property_type']).count().reset_index().drop(columns='review_scores_rating')
matching_table['cluster_id']=matching_table.index

In [ ]:
matching_table

In [ ]:
matching_table.to_csv('clusters_table.csv')

In [ ]:
percentiles

In [ ]:
top

In [ ]:
clusters[clusters['listing_id']== listing_id]

In [ ]:
test = listings[listings['id'] == int(53242)].to_dict('records')

In [ ]:
test[0]['neighbourhood_cleansed']

In [ ]:
listings.head(50)

In [79]:
def property_cat(ptype, psize):
    '''Transforms property type and size into a property cluster category'''
    if ptype != 'Entire home/apt':
        return 'room'
    elif psize < 2:
        return 'small'
    return 'large'

def price_cat(x,pctl):
    '''Transforms an absolute price into a price category, given a list of percentiles'''
    if x <pctl[1]:
        return 'very_cheap'
    elif x >=pctl[1] and x <pctl[3]:
        return 'cheap'
    elif x >=pctl[3] and x <pctl[5]:
        return 'average'
    elif x >=pctl[5] and x <pctl[7]:
        return 'expensive'
    return 'very_expensive'

def user_ranking_new(location, price, ptype, psize, listing_id, clusters, percentiles):
    '''Takes as input a neighborhood, a price, a listing property type, the listing id and the clusters dataframe
    returns:
    - the listing's ranking within its cluster
    - the cluster's average rating
    - the cluster size
    '''

    price_c=price_cat(price,percentiles[location])
    size_c = property_cat(ptype, psize)

    cluster = clusters[(clusters['location'] == location ) &  (clusters['price-boroughwise'] == price_c ) &\
              (clusters['property_type'] == size_c )\
            ].reset_index()
    cluster['ranking'] = cluster['review_scores_rating'].rank(method='min',ascending=False,pct=True)
    cluster_average = cluster['review_scores_rating'].mean()
    user_rank =float(cluster[cluster['listing_id']== listing_id]['ranking'])
    return user_rank, cluster_average, cluster.shape[0]

user_ranking_new('Lambeth', 55, 'Private room', 1 ,53242, clusters, percentiles)

(0.2579034941763727, 93.85690515806988, 601)

In [70]:
#clusters=pd.read_csv('../data/jan/clusters.csv')

price_c=price_cat(55,percentiles['Lambeth'])
size_c = property_cat('Private room', 1)

cluster = clusters[(clusters['location'] == 'Lambeth' ) &  (clusters['price-boroughwise'] == price_c ) &\
              (clusters['property_type'] == size_c )\
            ].reset_index()
cluster['ranking'] = cluster['review_scores_rating'].rank(method='min',ascending=False,pct=True)

In [78]:
clusters=pd.read_csv('../data/jan/clusters.csv')

In [77]:
float(cluster[cluster['listing_id']==53242]['ranking'])

KeyError: (0, 'ranking')

In [80]:
clusters

,Unnamed: 0,location,price-boroughwise,property_type,review_scores_rating,listing_id,lat,lon,cluster
0,0,Lambeth,expensive,small,92.0,11551.0,51.46225,-0.11732,L:Lambeth_P:expensive_S:small
1,33,Lambeth,cheap,room,98.0,53242.0,51.47075,-0.12913,L:Lambeth_P:cheap_S:room
2,34,Lambeth,expensive,small,96.0,53245.0,51.47246,-0.12727,L:Lambeth_P:expensive_S:small
3,50,Lambeth,cheap,room,96.0,72913.0,51.48064,-0.11439,L:Lambeth_P:cheap_S:room
4,51,Lambeth,cheap,large,98.0,73431.0,51.46295,-0.11200,L:Lambeth_P:cheap_S:large
...,...,...,...,...,...,...,...,...,...
51743,51047,Sutton,expensive,small,100.0,39963193.0,51.35770,-0.13601,L:Sutton_P:expensive_S:small
51744,51074,Sutton,expensive,small,98.0,39988769.0,51.35737,-0.21677,L:Sutton_P:expensive_S:small
51745,51098,Sutton,very_expensive,small,40.0,40019636.0,51.37853,-0.21887,L:Sutton_P:very_expensive_S:small
51746,51255,Sutton,expensive,large,60.0,40147104.0,51.34812,-0.19767,L:Sutton_P:expensive_S:large
51747,51438,Sutton,expensive,small,88.0,40364721.0,51.35550,-0.21603,L:Sutton_P:expensive_S:small

In [66]:
user_rank =float(cluster[cluster['listing_id']== 53242].reset_index()['ranking'])

In [67]:
user_rank

0.2579034941763727

In [37]:
size_c

'room'

In [19]:
cluster_average = cluster['review_scores_rating'].mean()

In [20]:
cluster_average

93.85690515806988

In [42]:
cluster[cluster['listing_id']== 72913].iloc[0].loc['ranking']

0.41430948419301167